### ISSUE TITLE
Making post function public or finding an alternative to a custom api call

### ISSUE THREAD

**Issue by juanbrena** [minitriga/silverpeak_python#35]
This python module has been very helpful for my Silverpeak testing. Although it does not have every api call that I need. I have been accessing the private method '_get' to get what I need. I would like to discuss how we could incorporable a public get/post method. Either we can make the methods public or create a new method where the user can do a custom get/post call.

**Comment by minitriga** [comment]
@juanbrena This would be useful. I have not been working with this library recently so have not been adding endpoints. I chose to add endpoints because some save the user from doing menial tasks. 

I think a Get and Post endpoint would be useful. As well a Edge Connect GET and POST endpoint.
