### ISSUE TITLE
Need to support pass through of the the proxies keyword to the requests

### ISSUE THREAD

**Issue by dwmoran5104** [minitriga/silverpeak_python#37]
Trying to use this behind the corporate firewall.   I need to be able to set the proxies paramaeter to the requests session

**Comment by juanbrena** [comment]
@dwmoran5104 Checkout my [add-proxies-to-requests-session branch](https://github.com/juanbrena/silverpeak_python/tree/add-proxies-to-requests-session). This should solve it. Let me know if it works for you. Thanks.

**Comment by minitriga** [comment]
@juanbrena Could you please create a merge request for this please?
