### ISSUE TITLE
Schema to deploy EdgeConnect Appliance.

### ISSUE THREAD

**Issue by surajano** [minitriga/silverpeak_python#40]
While deploying the EdgeConnect Appliance it throws Bad request, when I called 
`post_deployment_data` method, the value of `deploymentData` is passed having following schema `{
  "scalars": "Scalars",
  "sysConfig": {
    "mode": "",
    "useMgmt0": false,
    "tenG": false,
    "bonding": false,
    "maxBW": 0,
    "propagateLinkDown": false,
    "singleBridge": false,
    "inline": false,
    "ifLabels": {
      "lan": [
        {
          "id": 0,
          "name": ""
        }
      ],
      "wan": [
        {
          "id": 0,
          "name": ""
        }
      ]
    },
    "haIf": "",
    "maxInBW": 0,
    "maxInBWEnabled": false,
    "licence": {
      "ecMini": false,
      "ecPlus": false,
      "ecTier": "",
      "ecTierBW": 0,
      "ecBoost": false,
      "ecBoostBW": 0
    },
    "zones": [
      "fwZone"
    ]
  },
  "mgmtIfData": {
    "(ifName)": {
      "dhcp": false,
      "nexthop": "",
      "ip": "",
      "mask": 0
    }
  },
  "modeIfs": [
    {
      "devNum": "",
      "ifName": "",
      "applianceIPs": [
        {
          "ip": "",
          "mask": 0,
          "subif": "",
          "vlan": "",
          "wanNexthop": "",
          "label": "",
          "lanSide": false,
          "wanSide": false,
          "dhcp": false,
          "harden": 0,
          "behindNAT": "",
          "maxBW": "maxBW",
          "dhcpd": "dhcpd",
          "brifs": "brifs",
          "zone": 0,
          "comment": ""
        }
      ]
    }
  ],
  "dpRoutes": [
    {
      "prefix": "",
      "nexthop": "",
      "intf": "",
      "metric": 0,
      "type": ""
    }
  ],
  "vifs": {
    "pppoe": [
      ""
    ]
  },
  "dhcpFailover": {
    "(ifname)": {
      "max_unack_updates": 0,
      "peer_port": 0,
      "my_port": 0,
      "max_resp_delay": 0,
      "load_bal_max": 0,
      "role": "",
      "mclt": 0,
      "split": 0,
      "peer_ip": "",
      "my_ip": ""
    }
  }
}` 

I have check Swagger API but there is no API documented for deployment under `deployment : VXOA deployment configuration`

I have check  "ORCHESTRATOR REST API REFERENCE GUIDE" but there is no documentation for deploying the EdgeConnect Appliance.

Can anybody guide me with the schema/sample dict that is required ?
Can someone please help me with this ?

**Comment by juanbrena** [comment]
Can you provide a snippet of your code please? 

You are right. There is no API documentation for a POST deployment data call. Although, there is one. You can see it if you look through the Network Monitor, a Web Development tool Firefox offers (macOS shortcut: Cmd+Opt+E) . Chrome has something similar. In there you can see the information of exactly what is being called with what headers, params, etc.

**Comment by surajano** [comment]
Sorry for the late reply !!
@juanbrena : Thanks a ton!
This issue is resolved I inspected the web development too and under the network tab verified the request body.
changed my code accordingly and it work like a charm !

**Comment by juanbrena** [comment]
@surajano Awesome! Glad the network helped.
